name: CI/CD

on:
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t tohafrit/web:${{ github.sha }} .
          
      - name: Push Docker image
        run: docker push tohafrit/web:${{ github.sha }}

      - name: Set up Kubernetes
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ env.KUBE_CONFIG_DATA }}

      - name: Prepare deployment file
        run: sed -i 's|tohafrit/web:.*|tohafrit/web:${{ github.sha }}|g' deploy.yaml

      - name: Deploy to Kubernetes
        run: kubectl apply -f deploy.yaml
